# Schema for the configuration file of message module.
message.settings:
  type: config_object
  label: 'message Content Type Settings'
  mapping:
    allowed_types:
      type: sequence
      label: 'Content types message Form can display on'
      sequence:
        type: string
        label: 'Content type'